### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by ZhouCX117** [huhengtong/one-bit-supervision#1]
Hi, thanks for your excellent work!  Could you please provide the used CIFAR100 dataset or dataset structure? I download the initial PyTorch version but can't work. Looking forward to your answer!

**Comment by ZhouCX117** [comment]
By the way, how to generate ".npy" file in stage 1 and stage2? And what is the difference between "pred_false_stage1" and "false_pred_stage1"?

**Comment by ZhouCX117** [comment]
Hi, I have solved the above two questions.  The new one is that do we have to have the full label to judge whether the guess is true?

**Comment by huhengtong** [comment]
Thanks for your interest! We do need the full labels (ground truth) to judge the correctness of guesses, to imitate the process of human annotating.

**Comment by ZhouCX117** [comment]
Okay, thanks for your answer. I am going to follow your next works "VBUE" and "ObCP". Have a good day!
